// Generated by CoffeeScript 1.6.3
var Automator;

Automator = (function() {
  Automator.prototype.options = {
    namespace: "automator"
  };

  function Automator(datastore, options) {
    if (options == null) {
      options = {};
    }
    $.extend(this.options, options);
    this.datastore = datastore;
    this.categories = datastore.getTable("" + this.options.namespace + "-categories");
    this.words = datastore.getTable("" + this.options.namespace + "-words");
  }

  Automator.prototype.train = function(text, category) {
    var words;
    words = text.split(" ");
    this._increment(this.categories, category);
    _.map(words, function(word) {
      var categoryCounts, count, record;
      record = this._increment(this.words, word);
      categoryCounts = record.get("categories" || {});
      count = categoryCounts[category] || 0;
      categoryCounts[category] = count + 1;
      return record.set("categories", categoryCounts);
    });
  };

  Automator.prototype.classify = function(text) {
    return {
      classification: {
        category: "unknown",
        reason: [],
        confidence: 0
      }
    };
  };

  Automator.prototype._increment = function(table, name) {
    var count, record, records;
    records = table.query({
      name: name
    });
    record = records[0];
    if (records.length < 1) {
      record = table.insert({
        name: name,
        count: 0
      });
    }
    count = record.get("count");
    record.set('count', count + 1);
    return record;
  };

  return Automator;

})();
