// Generated by CoffeeScript 1.6.3
var Automator;

Automator = (function() {
  Automator.prototype.options = {
    dropboxNamespace: "automator"
  };

  function Automator(datastore, options) {
    if (options == null) {
      options = {};
    }
    this.datastore = datastore;
    $.extend(this.options, options);
  }

  Automator.prototype.train = function(text, category) {};

  Automator.prototype.classify = function(text) {
    return {
      classification: {
        category: "unknown",
        reason: [],
        confidence: 0
      }
    };
  };

  return Automator;

})();
